---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
components:
  - ../../components/common/sops
resources:
  - ./namespace.yaml
  - ../../components/common/sops
  - ./glance/igor/kustomization.yaml
