---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../../components/common/sops
  - ./namespace.yaml
  - ./glance/kustomization.yaml
  - ./flame/kustomization.yaml
  - ./nzbget/kustomization.yaml
  - ./radarr/kustomization.yaml
  - ./sonarr/kustomization.yaml
  - ./qbittorrent/kustomization.yaml
  - ./plex/kustomization.yaml
  # - ./invoiceninja/kustomization.yaml
  - ./librechat/kustomization.yaml
  - ./meilisearch/kustomization.yaml
