---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-analytics-mcp-creds
  namespace: librechat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: google-analytics-mcp-creds
        property: auth.json
