apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-google-saml-cert
  namespace: librechat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: librechat-google-saml-cert
        property: saml.pem
