---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-google-vertexai-creds
  namespace: librechat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: librechat-vertexai-sa
        property: auth.json
