---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: librechat-config
    files:
      - resources/librechat.yaml
generatorOptions:
  disableNameSuffixHash: true
