---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-operator
  namespace: mongodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mongodb-community-operator
    namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    community-operator-crds:
      enabled: true
    operator:
      resources:
        requests:
          cpu: 500m
          memory: 50Mi
        limits:
          memory: 100Mi
