---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: apps
spec:
  interval: 5m
  # renovate: registryUrl=http://bjw-s.github.io/helm-charts/
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      plex:
        strategy: RollingUpdate

        replicas: 1

        containers:
          app:
            image:
              repository: linuxserver/plex
              tag: 1.41.8
            env:
              TZ: "Europe/Belgrade"
              # PLEX_NO_AUTH_NETWORKS: 10.0.0.0/8
              VERSION: "docker"
              PLEX_ADVERTISE_URL: https://plex.hrcek.rs:443,https://10.40.0.5:32400
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 200m
                memory: 256Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 4096Mi

    service:
      app:
        controller: &app plex
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: "10.40.0.5"
        ports:
          http:
            port: &port 32400

    route:
      app:
        hostnames:
          - plex.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        existingClaim: plex-config
      transcode:
        type: emptyDir
        medium: Memory
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.10.0.2"
            path: "/var/nfs/shared/Media"
        globalMounts:
          - path: "/media"
