---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flame
  namespace: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      flame:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        containers:
          app:
            image:
              repository: pawelmalak/flame
              tag: 2.3.1
            envFrom:
              - secretRef:
                  name: flame-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    service:
      app:
        controller: &app flame
        ports:
          http:
            port: &port 5005

    route:
      app:
        hostnames:
          - koala.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        existingClaim: flame-config
        advancedMounts:
          flame:
            app:
              - path: /app/data
