# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb-librechat
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app mongodb-librechat
  path: ./kubernetes/apps/database/mongodb/librechat/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      MONGO_APP: *app
      # renovate: datasource=docker depName=mongodb/mongodb-community-server
      MONGO_VERSION: 8.0.5
      MONGO_VERSION_COMPATIBILITY: "8.0"
      MONGO_SECRET_FROM: spotify
      MONGO_DB: librechat
      MONGO_USER: librechat
