---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect-deployment
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
