# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yDOIL/Tuir+wztBiR8IZ/uV4yE3Kbg8TGouueXuHeHuvWbzcnbe0Vw==,iv:1Z9h+Mu9Zuivqesr01DJNnwLX3vHTr/ZSkbtZXK/Tdc=,tag:F25A2UvuzFuJlPrV6U47SA==,type:str]
sops:
  age:
    - recipient: age1t3zzpp4yht0spmdy679s4ht07h6xs0rve9kleyrw7zpn3z4zq9fqrgpujr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMjNuWm1CcWhMK1FIVlpY
        TERNQ1llODQ1emVvSVZnNWp4RnVoUVdoR1FrCnJ0NW5QUHlJdTliNWN4Z3JRWEx4
        TG1zYnMzcGFIOWxYL3ZGK055RXNhTXMKLS0tIE81a3ZmcDV1aDF4T2E4MTAxWW0r
        MGllZVM4czhzeGdzcXRXcmhweWF0YjAKiEE5CPM7KWfaugb31yycIRkskwpez7fY
        Johs18I/wN9a14gMaNYqE8QfSeJJ+xWi6wRP8aNiZ3IRSH0Y/YQwjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-14T20:42:13Z"
  mac: ENC[AES256_GCM,data:ul9qEfv9zccBrN4SV9QOdevCuQuza0Qf9K9DYkGFzR2d4WUZdaRvlMYIinx7Wr8nVHZHjQW7HGmTovmd3OPA7sdEA1ANTPMbXhos8D9FKxC/FCce7HUdYtvVg+YGoY7Lp0RsNbUWUGfoD8mwIXtwwzOVy+Levj0c/JFYxGZ84pE=,iv:bv0OXrblmQyncOs3zf1FslVUezBwdluLXwoCJ0TDN6E=,tag:h4gI9xLBhjYd7/DWuUFU2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
