apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-victoria-metrics
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://vmselect-victoria-metrics-vm.monitoring.svc:8481/select/0/prometheus
