---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-victoria-logs
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: VictoriaLogs
      type: victoriametrics-logs-datasource
      access: proxy
      url: http://victoria-logs-victoria-logs-single-server.monitoring.svc:9428
