---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./secret.yaml
  - ./helmrelease.yaml
  - ./datasource-victoria-logs.yaml
  - ./datasource-victoria-metrics.yaml
