---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 5m
  # renovate: registryUrl=http://bjw-s.github.io/helm-charts/
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      qbittorrent:
        strategy: RollingUpdate

        replicas: 1

        containers:
          app:
            image:
              repository: linuxserver/qbittorrent
              tag: 20.04.1
            env:
              TZ: "Europe/Belgrade"

    service:
      app:
        controller: &app qbittorrent
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - qbittorrent.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      # config:
      #   existingClaim: qbittorrent-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.10.0.2"
            path: "/var/nfs/shared/Media"
        globalMounts:
          - path: "/media"
