---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: victoriametrics
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: victoriametrics
    kubeControllerManager:
      enabled: true
      endpoints: []
      service:
        enabled: true
        port: 10257
        targetPort: 10257
        selector:
          component: kube-controller-manager
      vmScrape:
        spec:
          jobLabel: jobLabel
          namespaceSelector:
            matchNames:
              - kube-system
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                serverName: kubernetes
    grafana:
      enabled: false

    victoria-metrics-operator:
      enabled: true
      operator:
        disable_prometheus_converter: false
        enable_converter_ownership: true

    serviceAccount:
      create: true
      annotations: {}

    defaultRules:
      create: false

    alertmanager:
      enabled: true
      ingress:
        enabled: false
      monzoTemplate:
        enabled: true

      spec:
        disableNamespaceMatcher: true
        externalURL: "https://alrtmngr.hrcek.rs"
        disableRouteContinueEnforce: true

      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ["alertname"]
          group_wait: 1m
          group_interval: 5m
          repeat_interval: 3h
          receiver: devnull
          routes:
            - receiver: blackhole
              matchers:
                - "severity=blackhole"
              continue: true
        receivers:
          - name: devnull
          - name: blackhole

    vmalert:
      enabled: true
      remoteWriteVMAgent: false
      spec:
        selectAllByDefault: true

        evaluationInterval: 15s
      ingress:
        enabled: false

    vmagent:
      enabled: true
      # spec:
      #   inlineScrapeConfig: |
      #     - job_name: node-exporter
      #       honor_labels: true
      #       scrape_interval: 1m
      #       scrape_timeout: 10s
      #       metrics_path: /metrics
      #       scheme: http
      #       static_configs:
      #         - targets:
      #             - "10.5.0.32:9100"
        # selectAllByDefault: true
        # scrapeInterval: 25s
        # extraArgs:
        #   promscrape.streamParse: "true"
      ingress:
        enabled: false

    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
    kubelet:
      enabled: true
    kubeApiServer:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: true
      endpoints: []
      service:
        enabled: true
        port: 10259
        targetPort: 10259
        selector:
          component: kube-scheduler
      vmScrape:
        spec:
          jobLabel: jobLabel
          namespaceSelector:
            matchNames: [kube-system]
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
