---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/kustomization.yaml
  - ./victoriametrics/kustomization.yaml
  - ./grafana/kustomization.yaml
