---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      invoiceninja:
        strategy: RollingUpdate

        annotations:
          secret.reloader.stakater.com/reload: "invoiceninja-secret"
          configmap.reloader.stakater.com/reload: "invoiceninja-nginx-config"

        replicas: 1

        containers:
          app:
            image:
              repository: invoiceninja/invoiceninja-debian
              tag: 5.12
            envFrom:
              - secretRef:
                  name: invoiceninja-secret

          nginx:
            image:
              repository: nginx
              tag: alpine

    service:
      app:
        controller: &app invoiceninja
        ports:
          http:
            port: &port 8000

    route:
      app:
        hostnames:
          - invoices.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      public:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: openebs-hostpath
        advancedMounts:
          invoiceninja:
            app:
              - path: /var/www/html/public
            nginx:
              - path: /var/www/html/public
                readOnly: true

      storage:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: openebs-hostpath
        advancedMounts:
          invoiceninja:
            app:
              - path: /var/www/html/storage
            nginx:
              - path: /var/www/html/storage
                readOnly: true

      config:
        enabled: true
        type: configMap
        name: invoiceninja-nginx-config
        advancedMounts:
          invoiceninja:
            nginx:
              - path: /etc/nginx/conf.d/default.conf
                readOnly: true
                subPath: default.conf
