---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      invoiceninja:
        strategy: RollingUpdate

        replicas: 1

        containers:
          app:
            image:
              repository: invoiceninja/invoiceninja-debian
              tag: 5.12
            envFrom:
              - secretRef:
                  name: invoiceninja-secret

    service:
      app:
        controller: &app invoiceninja
        ports:
          http:
            port: &port 9000

    route:
      app:
        hostnames:
          - invoices.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    # persistence:
    #   storage:
    #     enabled: true
    #     type: custom
    #     volumeSpec:
    #       ephemeral:
    #         volumeClaimTemplate:
    #           spec:
    #             accessModes:
    #               - ReadWriteOnce
    #             storageClassName: "openebs-hostpath"
    #             resources:
    #               requests:
    #                 storage: 10Gi
    #     globalMounts:
    #       - path: "/var/app/public"
