---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: apps
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      invoiceninja:
        strategy: RollingUpdate

        replicas: 1

        containers:
          app:
            image:
              repository: invoiceninja/invoiceninja-debian
              tag: 5.12
            envFrom:
              - secretRef:
                  name: invoiceninja-secret

    service:
      app:
        controller: &app invoiceninja
        ports:
          http:
            port: &port 9000

    route:
      app:
        hostnames:
          - invoices.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      temp:
        type: emptyDir
        advancedMounts:
          invoiceninja:
            app:
              - path: /tmp
      public:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: openebs-hostpath
        globalMounts:
          - path: /var/www/html/public

      storage:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: openebs-hostpath
        globalMounts:
          - path: /var/www/html/storage
