apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhooks-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: monitoring-webhooks
