apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: database
spec:
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb
        namespace: flux-system
      version: 25.8.3
  interval: 1h0m0s
  values:
    crds:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
