---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./vernemq/kustomization.yaml
  - ./zigbee2mqtt/kustomization.yaml
  - ./homeassistant/kustomization.yaml
