{
 "title": "Monitoring / Alertmanager / Summary",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "monitoring",
  "alertmanager",
  "summary"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(alertmanager_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Notifications sent from $instance",
   "type": "timeseries",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$__interval])) by (integration)",
     "legendFormat": "{{ integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$__interval])) by (integration)",
     "legendFormat": "Failed {{ integration }}"
    }
   ]
  },
  {
   "title": "Alerts and SIlences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received alerts by status for $instance",
   "type": "timeseries",
   "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$instance\"}[$__interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Silences query count on $instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(alertmanager_silences_queries_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Silecnces query count"
    },
    {
     "expr": "increase(alertmanager_silences_query_errors_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Silecnces query fails"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage/s for $instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage for $instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  }
 ]
}