apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-kubelet-rules
  namespace: monitoring
spec:
  "groups":
  - "name": |-
          kubernetes.kubelet.rules
        "rules":
          - "alert": |-
                      KubeNodeNotReady
                    "annotations":
                      "description": |
                        `{{ $labels.node }}` has been unready for more than 15 minutes.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodenotready
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Node is not ready.
                    "expr": |
                      kube_node_status_condition{job="kube-state-metrics",condition="Ready",status="true"} == 0
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeNodeUnreachable
                    "annotations":
                      "description": |
                        `{{ $labels.node }}` is unreachable and some workloads may be rescheduled.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodeunreachable
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Node is unreachable.
                    "expr": |
                      (kube_node_spec_taint{job="kube-state-metrics",key="node.kubernetes.io/unreachable",effect="NoSchedule"} unless ignoring(key,value) kube_node_spec_taint{job="kube-state-metrics",key=~"ToBeDeletedByClusterAutoscaler|cloud.google.com/impending-node-termination|aws-node-termination-handler/spot-itn"}) == 1
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletTooManyPods
                    "annotations":
                      "description": |
                        Kubelet `{{ $labels.node }}` is running at `{{ $value | humanizePercentage }}` of its Pod capacity.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubelettoomanypods
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet is running at capacity.
                    "expr": |
                      count by(cluster, node) (
                        (kube_pod_status_phase{job="kube-state-metrics",phase="Running"} == 1) * on(instance,pod,namespace,cluster) group_left(node) topk by(instance,pod,namespace,cluster) (1, kube_pod_info{job="kube-state-metrics"})
                      )
                      /
                      max by(cluster, node) (
                        kube_node_status_capacity{job="kube-state-metrics",resource="pods"} != 1
                      ) > 0.95
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        info
          - "alert": |-
                      KubeNodeReadinessFlapping
                    "annotations":
                      "description": |
                        The readiness status of node `{{ $labels.node }}` has changed `{{ $value }}` times in the last 15 minutes.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubenodereadinessflapping
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Node readiness status is flapping.
                    "expr": |
                      sum(changes(kube_node_status_condition{job="kube-state-metrics",status="true",condition="Ready"}[15m])) by (cluster, node) > 2
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletPlegDurationHigh
                    "annotations":
                      "description": |
                        The Kubelet Pod Lifecycle Event Generator has a 99th percentile duration of `{{ $value }}` seconds on node `{{ $labels.node }}`.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletplegdurationhigh
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet Pod Lifecycle Event Generator is taking too long to relist.
                    "expr": |
                      node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile{quantile="0.99"} >= 10
                    "for": |-
                      5m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletPodStartUpLatencyHigh
                    "annotations":
                      "description": |
                        Kubelet Pod startup 99th percentile latency is `{{ $value }}` seconds on node `{{ $labels.node }}`.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletpodstartuplatencyhigh
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet Pod startup latency is too high.
                    "expr": |
                      histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{job="kubelet"}[5m])) by (cluster, instance, le)) * on(cluster, instance) group_left(node) kubelet_node_name{job="kubelet"} > 60
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletClientCertificateExpiration
                    "annotations":
                      "description": |
                        Client certificate for Kubelet on node `{{ $labels.node }}` expires in `{{ $value | humanizeDuration }}`.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletclientcertificateexpiration
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet client certificate is about to expire.
                    "expr": |
                      kubelet_certificate_manager_client_ttl_seconds < 604800
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletClientCertificateExpiration
                    "annotations":
                      "description": |
                        Client certificate for Kubelet on node `{{ $labels.node }}` expires in `{{ $value | humanizeDuration }}`.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletclientcertificateexpiration
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet client certificate is about to expire.
                    "expr": |
                      kubelet_certificate_manager_client_ttl_seconds < 86400
                    "labels":
                      "severity": |-
                        critical
                      "robusta_incidentio_severity": |-
                        minor
          - "alert": |-
                      KubeletServerCertificateExpiration
                    "annotations":
                      "description": |
                        Server certificate for Kubelet on node `{{ $labels.node }}` expires in `{{ $value | humanizeDuration }}`.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletservercertificateexpiration
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet server certificate is about to expire.
                    "expr": |
                      kubelet_certificate_manager_server_ttl_seconds < 604800
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletServerCertificateExpiration
                    "annotations":
                      "description": |
                        Server certificate for Kubelet on node `{{ $labels.node }}` expires in `{{ $value | humanizeDuration }}`.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletservercertificateexpiration
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet server certificate is about to expire.
                    "expr": |
                      kubelet_certificate_manager_server_ttl_seconds < 86400
                    "labels":
                      "severity": |-
                        critical
                      "robusta_incidentio_severity": |-
                        minor
          - "alert": |-
                      KubeletClientCertificateRenewalErrors
                    "annotations":
                      "description": |
                        Kubelet on node `{{ $labels.node }}` has failed to renew its client certificate (`{{ $value | humanize }}` errors in the last 5 minutes).
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletclientcertificaterenewalerrors
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet has failed to renew its client certificate.
                    "expr": |
                      increase(kubelet_certificate_manager_client_expiration_renew_errors[5m]) > 0
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletServerCertificateRenewalErrors
                    "annotations":
                      "description": |
                        Kubelet on node `{{ $labels.node }}` has failed to renew its server certificate (`{{ $value | humanize }}` errors in the last 5 minutes).
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletservercertificaterenewalerrors
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Kubelet has failed to renew its server certificate.
                    "expr": |
                      increase(kubelet_server_expiration_renew_errors[5m]) > 0
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        warning
          - "alert": |-
                      KubeletDown
                    "annotations":
                      "description": |
                        Kubelet has disappeared from Prometheus target discovery.
                      "runbook_url": |
                        https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletdown
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
                      "summary": |-
                        Target disappeared from Prometheus target discovery.
                    "expr": |
                      absent(up{job="kubelet"} == 1)
                    "for": |-
                      15m
                    "labels":
                      "severity": |-
                        critical
                      "robusta_incidentio_severity": |-
                        critical
          - "alert": |-
                      KubeNodeOutOfCapacity
                    "expr": |
                      sum(kube_pod_info) by (node,environment) / sum(kube_node_status_capacity{resource="pods"}) by (node,environment) * 100 > 90
                    "for": |-
                      5m
                    "labels":
                      "severity": |-
                        critical
                      "robusta_incidentio_severity": |-
                        minor
                    "annotations":
                      "summary": |-
                        Kubernetes node is out of capacity
                      "description": |
                        The node `{{ $labels.node }}` capacity is at `{{ $value }}%` of it's total capacity.
                      "runbook_url": |-
                        https://runbook.mailergroup.com/KubernetesNodeOutOfCapacity
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-kubelet/kubernetes-kubelet
          - "alert": |-
                      KubeNodeAdded
                    "expr": |
                      kubelet_node_name * on (node) group_left(instance) ((time() - kube_node_created) / 60) < 10
                    "labels":
                      "severity": |-
                        notification
                    "annotations":
                      "description": |
                        A new node `{{ $labels.node }}` on `{{ $labels.cluster }}`{{ if $labels.component }} (component `{{ $labels.component }}`){{end}} has been added in the last `10 minutes`.
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-views-nodes/kubernetes-views-nodes
          - "alert": |-
                      KubeNodeRemoved
                    "expr": |
                      max(kube_node_info offset 10m) by (cluster, node) unless max(kube_node_info) by (cluster, node)
                    "labels":
                      "severity": |-
                        notification
                    "annotations":
                      "description": |
                        The node `{{ $labels.node }}` on `{{ $labels.cluster }}` has been removed in the last `10 minutes`.
                      "dashboard_url": |-
                        {{ $labels.grafana_url }}/d/k8s-views-nodes/kubernetes-views-nodes
