apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-storage-rules
  namespace: monitoring
spec:
  "groups":
  - "name": |-
      kubernetes.storage.rules
    "rules":
    - "alert": |-
        KubePersistentVolumeFillingUp
      "annotations":
        "dashboard_url": |-
          {{ $labels.grafana_url }}/d/k8s-persistent-volumes/kubernetes-persistent-volumes
        "description": |
          The PersistentVolume claimed by `{{ $labels.persistentvolumeclaim }}` in Namespace `{{ $labels.namespace }}` {{ with $labels.cluster -}} on Cluster `{{ . }}` {{- end }} is only `{{ $value | humanizePercentage }}` free.
        "runbook_url": |-
          https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumefillingup
        "summary": |-
          PersistentVolume is filling up.
      "expr": |
        (
          kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 0.03
        and
        kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": |-
        1m
      "labels":
        "robusta_incidentio_severity": |-
          major
        "severity": |-
          critical
    - "alert": |-
        KubePersistentVolumeFillingUp
      "annotations":
        "dashboard_url": |-
          {{ $labels.grafana_url }}/d/k8s-persistent-volumes/kubernetes-persistent-volumes
        "description": |
          Based on recent sampling, the PersistentVolume claimed by `{{ $labels.persistentvolumeclaim }}` in Namespace `{{ $labels.namespace }}` {{ with $labels.cluster -}} on Cluster `{{ . }}` {{- end }} is expected to fill up within four days. Currently `{{ $value | humanizePercentage }}` is available.
        "runbook_url": |-
          https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumefillingup
        "summary": |-
          PersistentVolume is filling up.
      "expr": |
        (
          kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 0.15
        and
        kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        and
        predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": |-
        1h
      "labels":
        "severity": |-
          warning
    - "alert": |-
        KubePersistentVolumeInodesFillingUp
      "annotations":
        "dashboard_url": |-
          {{ $labels.grafana_url }}/d/k8s-persistent-volumes/kubernetes-persistent-volumes
        "description": |
          The PersistentVolume claimed by `{{ $labels.persistentvolumeclaim }}` in Namespace `{{ $labels.namespace }}` `{{ with $labels.cluster -}}` on Cluster `{{ . }}` `{{- end }}` only has `{{ $value | humanizePercentage }}` free inodes.
        "runbook_url": |-
          https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeinodesfillingup
        "summary": |-
          PersistentVolumeInodes are filling up.
      "expr": |
        (
          kubelet_volume_stats_inodes_free{job="kubelet"}
            /
          kubelet_volume_stats_inodes{job="kubelet"}
        ) < 0.03
        and
        kubelet_volume_stats_inodes_used{job="kubelet"} > 0
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": |-
        1m
      "labels":
        "robusta_enrichment_graph": |-
          true
        "robusta_enrichment_graph_format": |-
          Percentage
        "robusta_incidentio_severity": |-
          major
        "severity": |-
          critical
    - "alert": |-
        KubePersistentVolumeInodesFillingUp
      "annotations":
        "dashboard_url": |-
          {{ $labels.grafana_url }}/d/k8s-persistent-volumes/kubernetes-persistent-volumes
        "description": |
          Based on recent sampling, the PersistentVolume claimed by `{{ $labels.persistentvolumeclaim }}` in Namespace `{{ $labels.namespace }}` `{{ with $labels.cluster -}}` on Cluster `{{ . }}` `{{- end }}` is expected to run out of inodes within four days. Currently `{{ $value | humanizePercentage }}` of its inodes are free.
        "runbook_url": |-
          https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeinodesfillingup
        "summary": |-
          PersistentVolumeInodes are filling up.
      "expr": |
        (
          kubelet_volume_stats_inodes_free{job="kubelet"}
            /
          kubelet_volume_stats_inodes{job="kubelet"}
        ) < 0.15
        and
        kubelet_volume_stats_inodes_used{job="kubelet"} > 0
        and
        predict_linear(kubelet_volume_stats_inodes_free{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(cluster, namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      "for": |-
        1h
      "labels":
        "robusta_enrichment_graph": |-
          true
        "robusta_enrichment_graph_format": |-
          Percentage
        "severity": |-
          warning
    - "alert": |-
        KubePersistentVolumeErrors
      "annotations":
        "dashboard_url": |-
          {{ $labels.grafana_url }}/d/k8s-persistent-volumes/kubernetes-persistent-volumes
        "description": |
          The persistent volume `{{ $labels.persistentvolume }}` {{ with $labels.cluster -}} on Cluster `{{ . }}` {{- end }} has status `{{ $labels.phase }}`.
        "runbook_url": |-
          https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeerrors
        "summary": |-
          PersistentVolume is having issues with provisioning.
      "expr": |
        kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kube-state-metrics"} > 0
      "for": |-
        5m
      "labels":
        "robusta_incidentio_severity": |-
          major
        "severity": |-
          critical
    - "alert": |-
        KubePersistentvolumeclaimPending
      "annotations":
        "dashboard_url": |-
          {{ $labels.grafana_url }}/d/k8s-persistent-volumes/kubernetes-persistent-volumes
        "description": |
          PersistentVolumeClaim `{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }}` is pending state for the last `5 minutes`.
        "summary": |-
          Kubernetes PersistentVolumeClaim is pending state
      "expr": |-
        kube_persistentvolumeclaim_status_phase{phase="Pending"} == 1
      "for": |-
        5m
      "labels":
        "severity": |-
          warning
