apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: monitoring-blackbox
  namespace: monitoring
spec:
  "groups":
  -
    "name": |-
      blackbox.rules
    "rules":
      -
        "alert": |-
          BlackboxProbeDurationHigh
        "expr": |-
          probe_duration_seconds{job="blackbox-exporter"} > 35
        "for": |-
          1m
        "labels":
          "severity": |-
            warning
        "annotations":
          "summary": |-
            Blackbox probe for instance `{{ $labels.instance }}` took too long
          "description": |-
            Blackbox probe for instance `{{ $labels.instance }}` took more than `30s` to complete. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
          "runbook_url": |-
            https://runbook.mailergroup.com/BlackboxProbeFailed
      -
        "alert": |-
          BlackboxProbeHttpFailure
        "expr": |-
          probe_http_status_code <= 199 OR probe_http_status_code >= 400
        "for": |-
          15m
        "labels":
          "severity": |-
            critical
          "robusta_incidentio_severity": |-
            major
        "annotations":
          "summary": |-
            Blackbox probe HTTP failure for instance `{{ $labels.instance }}`
          "description": |-
            Blackbox probe for instance `{{ $labels.instance }}` failed with HTTP status code `{{ $value }}`. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
          "runbook_url": |-
            https://runbook.mailergroup.com/BlackboxProbeFailed
      -
        "alert": |-
          BlackboxProbeDNSFailure
        "expr": |-
          probe_dns_lookup_time_seconds{job="blackbox-exporter"} > 5
        "for": |-
          1m
        "labels":
          "severity": |-
            warning
        "annotations":
          "summary": |-
            Blackbox DNS resolution for instance `{{ $labels.instance }}` took too long
          "description": |-
            Blackbox was unable to perform DNS resolution for instance `{{ $labels.instance }}`, which took more than `5s` to complete. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
          "runbook_url": |-
            https://runbook.mailergroup.com/BlackboxProbeFailed
      -
        "alert": |-
          BlackboxProbeRedirectLoop
        "expr": |-
          increase(probe_http_redirects[5m]) > 10
        "for": |-
          5m
        "labels":
          "severity": |-
            warning
        "annotations":
          "summary": |-
            Redirect loop detected for instance `{{ $labels.instance }}`
          "description": |-
            Blackbox got stuck in redirect loop during checks for instance `{{ $labels.instance }}`. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
          "runbook_url": |-
            https://runbook.mailergroup.com/BlackboxProbeFailed
