apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: monitoring-blackbox-rules
  namespace: monitoring
spec:
  "groups":
  - "name": |-
      blackbox.rules
    "rules":
    - "alert": |-
        BlackboxProbeDurationHigh
      "annotations":
        "description": |
          Blackbox probe for instance `{{ $labels.instance }}` took more than `30s` to complete. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
        "summary": |-
          Blackbox probe for instance `{{ $labels.instance }}` took too long
      "expr": |-
        probe_duration_seconds{job="blackbox-exporter"} > 35
      "for": |-
        1m
      "labels":
        "severity": |-
          warning
    - "alert": |-
        BlackboxProbeHttpFailure
      "annotations":
        "description": |
          Blackbox probe for instance `{{ $labels.instance }}` failed with HTTP status code `{{ $value }}`. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
        "summary": |-
          Blackbox probe HTTP failure for instance `{{ $labels.instance }}`
      "expr": |-
        probe_http_status_code <= 199 OR probe_http_status_code >= 400
      "for": |-
        15m
      "labels":
        "robusta_incidentio_severity": |-
          major
        "severity": |-
          critical
    - "alert": |-
        BlackboxProbeDNSFailure
      "annotations":
        "description": |
          Blackbox was unable to perform DNS resolution for instance `{{ $labels.instance }}`, which took more than `5s` to complete. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
        "summary": |-
          Blackbox DNS resolution for instance `{{ $labels.instance }}` took too long
      "expr": |-
        probe_dns_lookup_time_seconds{job="blackbox-exporter"} > 5
      "for": |-
        1m
      "labels":
        "severity": |-
          warning
    - "alert": |-
        BlackboxProbeRedirectLoop
      "annotations":
        "description": |
          Blackbox got stuck in redirect loop during checks for instance `{{ $labels.instance }}`. This alert *should not be ignored* - please investigate the issue as quickly as possible using the linked runbook as a guide.
        "summary": |-
          Redirect loop detected for instance `{{ $labels.instance }}`
      "expr": |-
        increase(probe_http_redirects[5m]) > 10
      "for": |-
        5m
      "labels":
        "severity": |-
          warning
