---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./snapshot-controller/kustomization.yaml
  - ./onepassword-connect/kustomization.yaml
  - ./external-secrets/kustomization.yaml
  - ./volsync/kustomization.yaml
