# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.40.0.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - &talosControlplaneVip "10.40.0.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "edge001"
    ipAddress: "10.40.0.101"
    installDiskSelector:
      model: "Lexar SSD NQ100"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0649a881d8a50c3e70b4ec4b8ca459559f7dd681a5c1587f4b3bca70f7f870f3
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "58:47:ca:77:39:b1"
              driver: igc
        dhcp: true
        vip:
          ip: *talosControlplaneVip
        vlans:
          - vlanId: 1
            dhcp: false
            addresses:
              - 10.10.0.101/24
            mtu: 1500
          - vlanId: 20
            dhcp: false
            addresses:
              - 10.20.0.101/24
            mtu: 1500
  - hostname: "edge002"
    ipAddress: "10.40.0.102"
    installDiskSelector:
      model: "Lexar SSD NQ100"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0649a881d8a50c3e70b4ec4b8ca459559f7dd681a5c1587f4b3bca70f7f870f3
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "58:47:ca:77:36:b5"
              driver: igc
        dhcp: true
        vip:
          ip: *talosControlplaneVip
        vlans:
          - vlanId: 1
            dhcp: false
            addresses:
              - 10.10.0.102/24
            mtu: 1500
          - vlanId: 20
            dhcp: false
            addresses:
              - 10.20.0.102/24
            mtu: 1500
  - hostname: "edge003"
    ipAddress: "10.40.0.103"
    installDiskSelector:
      model: "Lexar SSD NQ100"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0649a881d8a50c3e70b4ec4b8ca459559f7dd681a5c1587f4b3bca70f7f870f3
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors:
            - hardwareAddr: "58:47:ca:7c:0e:61"
              driver: igc
        dhcp: true
        vip:
          ip: *talosControlplaneVip
        vlans:
          - vlanId: 1
            dhcp: false
            addresses:
              - 10.10.0.103/24
            mtu: 1500
          - vlanId: 20
            dhcp: false
            addresses:
              - 10.20.0.103/24
            mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/machine-openebs.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

