{
 "title": "Kubernetes / Networking / Ingress",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash,namespace)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"},controller_class)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\", controller_class=~\"$controller_class\"},controller_pod)"
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller=~\"$controller\"}, ingress) "
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",state=\"active\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(irate(nginx_ingress_controller_success{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{controller_pod=~\"$controller\",controller_namespace=~\"$namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}