{
 "title": "Kubernetes / Volumes / Performance",
 "tags": [
  "disk",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "base_iops_multiplier",
    "query": "premium-rwo : 6000, custom-ssd : 6000, standard-rwo : 3000, standard : 0"
   },
   {
    "name": "throughput_per_gb_multiplier",
    "query": "premium-rwo : 0.48, custom-ssd : 0.48, standard-rwo : 0.28, standard : 0.12"
   },
   {
    "name": "base_throughput_multiplier",
    "query": "premium-rwo : 240, custom-ssd : 240, standard-rwo : 140, standard : 0"
   },
   {
    "name": "iops_per_gb_multiplier",
    "query": "premium-rwo : 30, custom-ssd : 30, standard-rwo : 6, standard : 1.5 "
   },
   {
    "name": "pvc",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info,persistentvolumeclaim)"
    }
   },
   {
    "name": "sc",
    "label": "StorageClass",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{persistentvolumeclaim=\"$pvc\"},storageclass)"
    }
   },
   {
    "name": "base_throughput",
    "label": "Base Throughout MiBps",
    "query": {
     "query": "query_result(max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${base_throughput_multiplier:$sc})"
    }
   },
   {
    "name": "throughput_per_gb",
    "label": "Throughput Per GiB (MiBps)",
    "query": {
     "query": "query_result(max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${throughput_per_gb_multiplier:$sc})"
    }
   },
   {
    "name": "base_iops",
    "label": "Base IOPS",
    "query": {
     "query": "query_result(max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${base_iops_multiplier:$sc})"
    }
   },
   {
    "name": "iops_per_gb",
    "label": "IOPS Per GiB",
    "query": {
     "query": "query_result(max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${iops_per_gb_multiplier:$sc})"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(label_replace(kube_persistentvolume_capacity_bytes, \"volumename\", \"$1\", \"persistentvolume\", \"(.+)\") / (1024*1024*1024)) * on (volumename) group_left(instance,device, persistentvolumeclaim)\n(max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"$pvc\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Base Throughput (MB/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${base_throughput_multiplier:$sc}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput per Gib (MB/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${throughput_per_gb_multiplier:$sc}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Base IOPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${base_iops_multiplier:$sc}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS per GB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_persistentvolumeclaim_info{storageclass=\"${sc}\", persistentvolumeclaim=\"${pvc}\"}) * ${iops_per_gb_multiplier:$sc}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(instance, device) (rate(node_disk_io_time_seconds_total[5m])) * on (instance, device) group_left(persistentvolumeclaim, volumename)\n(max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"})",
     "legendFormat": "{{device}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Read / Write Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_read_bytes_total[5m]) / rate(node_disk_written_bytes_total[5m]))\n* on (instance, device)\n group_left(persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"})",
     "legendFormat": "Throughput"
    },
    {
     "expr": "sum by (instance, device) (rate(node_disk_reads_completed_total[5m]) / rate(node_disk_writes_completed_total[5m]))\n* on (instance, device)\n group_left(persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \"(.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"})",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Disk Throughput Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance, device) (rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m])) / (1024 * 1024))\n\n/ on (instance, device) group_left(volumename, persistentvolumeclaim)\n((${throughput_per_gb} * sum by (volumename) (label_replace(kube_persistentvolume_capacity_bytes, \"volumename\", \"$1\", \"persistentvolume\", \"(.+)\")) / (1024 * 1024 * 1024) + ${base_throughput} )  \n* on (volumename) group_left(instance, device, persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"}))",
     "legendFormat": "{{device}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Throughput in MBps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "(sum by (instance, device) (rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m])) / (1024 * 1024))\n* on (instance, device)\n group_left(persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\"))\n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"})",
     "legendFormat": "Current Throughput"
    },
    {
     "expr": "((${throughput_per_gb} * sum by (volumename) (label_replace(kube_persistentvolume_capacity_bytes, \"volumename\", \"$1\", \"persistentvolume\", \"(.+)\")) / (1024 * 1024 * 1024) + ${base_throughput} ) \n* on (volumename) group_left(instance, device, persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \"(.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"}))",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Disk IOPS Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_reads_completed_total[5m]) + rate(node_disk_writes_completed_total[5m]))\n\n/ on (instance, device) group_left(volumename, persistentvolumeclaim)\n((${iops_per_gb} * sum by (volumename) (label_replace(kube_persistentvolume_capacity_bytes, \"volumename\", \"$1\", \"persistentvolume\", \"(.+)\")) / (1024 * 1024 * 1024) + ${base_iops} ) \n* on (volumename) group_left(instance, device, persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"}))",
     "legendFormat": "{{device}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_reads_completed_total[5m]) + rate(node_disk_writes_completed_total[5m]))\n* on (instance, device)\n group_left(persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "((${iops_per_gb} * sum by (volumename) (label_replace(kube_persistentvolume_capacity_bytes, \"volumename\", \"$1\", \"persistentvolume\", \"(.+)\")) / (1024 * 1024 * 1024) + ${base_iops} ) \n* on (volumename) group_left(instance, device, persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \"(.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"}))",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Disk Usage Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"${pvc}\"} / on (persistentvolumeclaim) group_left(instance,device)\n(label_replace(kube_persistentvolume_capacity_bytes, \"volumename\", \"$1\", \"persistentvolume\", \"(.+)\") \n* on (volumename) group_left(instance,device, persistentvolumeclaim) (max by (instance, device, volumename) (label_replace(node_disk_info, \"volumename\", \"$1\", \"serial\", \".*(pvc.+)\")) \n* on (volumename) group_left(storageclass, persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=\"${pvc}\"}))",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}