---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashboard-igor
  namespace: services
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      dashboardigor:
        annotations:
          configmap.reloader.stakater.com/reload: "dashboard-igor-configuration"

        replicas: 1

        containers:
          app:
            image:
              repository: glanceapp/glance
              tag: v0.8.4
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    service:
      app:
        controller: &app dashboardigor
        ports:
          http:
            port: &port 8080

    persistence:
      config:
        enabled: true
        type: configMap
        name: dashboard-igor-configuration
        globalMounts:
          - path: /app/config/glance.yml
            subPath: glance.yml

    route:
      app:
        hostnames:
          - dash.hrcek.rs
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

