---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: vmlogs.hrcek.rs
    service: http://victoria-logs-victoria-logs-single-server.monitoring.svc.cluster.local:9428
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
