---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.mariadb.com/mariadb-operator
