---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nzbget-secret
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: nzbget-secret
  dataFrom:
    - extract:
        key: nzbget
