# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.2.8

fileStrategy: "s3"


endpoints:
  custom:
    - name: "OpenRouter"
      apiKey: "${OPENROUTER_KEY}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default: ["google/gemini-2.5-flash"]
        fetch: true
      titleConvo: true
      titleModel: "google/gemini-2.5-flash"
      dropParams: ["stop"]
      modelDisplayLabel: "OpenRouter"
