---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-secret
  namespace: home
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-secret
    template:
      engineVersion: v2
      data:
        MAKER_API_TOKEN: "{{ .MAKER_API_TOKEN }}"
  dataFrom:
    - extract:
        key: homeassistant
