---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: api-token
